name: Build

on:
  pull_request:
    branches: ["main", "develop", "stage"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/test_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

    steps:
      - name: Checkout WarrantyBee.API repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set environment
        run: |
          if [ "${{ github.base_ref }}" = "main" ]; then
            echo "SPRING_PROFILES_ACTIVE=Prod" >> $GITHUB_ENV
          elif [ "${{ github.base_ref }}" = "develop" ]; then
            echo "SPRING_PROFILES_ACTIVE=Test" >> $GITHUB_ENV
          elif [ "${{ github.base_ref }}" = "stage" ]; then
            echo "SPRING_PROFILES_ACTIVE=Stage" >> $GITHUB_ENV
          fi

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check MySQL Status
        run: |
          echo "Waiting for MySQL to start..."
          for i in {1..30}; do
            if mysqladmin ping -h "127.0.0.1" -uroot -proot --silent; then
              echo "âœ… MySQL is up!"
              break
            fi
            echo "Waiting..."
            sleep 2
          done

      - name: Build
        run: mvn -B clean package -Dmaven.test.skip=true
