# This workflow builds and pushes a Docker image to Docker Hub and then deploys it to Koyeb.
# The workflow is triggered on pushes to the main, stage, and develop branches.
#
# It uses GitHub environments to manage secrets and variables for different deployment targets:
# - `main` branch -> `Production` environment
# - `stage` branch -> `Stage` environment
# - `develop` branch -> `Test` environment
#
# Required secrets in each environment:
# - DOCKERHUB_USERNAME: Your Docker Hub username.
# - DOCKERHUB_TOKEN: Your Docker Hub access token.
# - KOYEB_TOKEN: Your Koyeb API token.
#
# Required variables in each environment:
# - KOYEB_APP_NAME: The name of your Koyeb app.
# - KOYEB_SERVICE_NAME: The name of the service within your Koyeb app to deploy to.
# - KOYEB_DOCKER_SECRET_NAME: The name of the Koyeb secret for your Docker private registry.

name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref_name == 'main' || github.ref_name == 'stage' || github.ref_name == 'develop'
    name: Deploy to ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.ref_name == 'main' && 'Production') || (github.ref_name == 'stage' && 'Stage') || 'Test' }}
      url: ${{ steps.deploy-to-koyeb.outputs.url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert branch name to lowercase
        id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.ref_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/warrantybee-api:${{ steps.string.outputs.lowercase }},${{ secrets.DOCKERHUB_USERNAME }}/warrantybee-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Koyeb
        id: deploy-to-koyeb
        uses: koyeb/action-deploy@v2
        with:
          koyeb_token: ${{ secrets.KOYEB_TOKEN }}
          app: ${{ vars.KOYEB_APP_NAME }}
          service: ${{ vars.KOYEB_SERVICE_NAME }}
          docker_image: "${{ secrets.DOCKERHUB_USERNAME }}/warrantybee-api:${{ github.sha }}"
          docker_private_registry_secret: ${{ vars.KOYEB_DOCKER_SECRET_NAME }}
