name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    if: github.ref_name == 'main' || github.ref_name == 'stage' || github.ref_name == 'develop'
    name: Deploy to ${{ github.ref_name }}
    runs-on: ubuntu-latest

    environment:
      name: ${{ (github.ref_name == 'main' && 'Prod') || (github.ref_name == 'stage' && 'Stage') || 'Test' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert branch name to lowercase
        id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.ref_name }}

      - name: Determine image name
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "IMAGE_NAME=warrantybee-api" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "stage" ]; then
            echo "IMAGE_NAME=warrantybee-api-stage" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" = "develop" ]; then
            echo "IMAGE_NAME=warrantybee-api-test" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.string.outputs.lowercase }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update image and redeploy on Koyeb
        run: |
          echo "Patching Koyeb service: ${{ vars.KOYEB_SERVICE_ID }}"

          curl -v -X PATCH "https://app.koyeb.com/v1/services/${{ vars.KOYEB_SERVICE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.KOYEB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
                  \"definition\": {
                    \"name\": \"warrantybee-api\",
                    \"regions\": [\"fra\"],
                    \"instance_types\": [
                      { \"type\": \"free\" }
                    ],
                    \"scalings\": [
                      {
                        \"metric\": \"cpu\",
                        \"target\": 60,
                        \"min\": 0,
                        \"max\": 1
                      }
                    ],
                    \"routes\": [
                      {
                        \"path\": \"/\",
                        \"port\": 8080
                      }
                    ],
                    \"container\": {
                      \"image\": \"${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}\",
                      \"private_registry\": {
                        \"secret\": \"${{ vars.KOYEB_DOCKER_SECRET_NAME }}\"
                      }
                    }
                  }
                }"
